# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ybahij <ybahij@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/05/20 11:16:59 by ybahij            #+#    #+#              #
#    Updated: 2024/05/20 11:52:56 by ybahij           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = philo
CC = cc
CFLAGS = -Wall -Wextra -Werror
SRC = extra_f3.c data_init.c extra_f.c parse_inpet.c thread_init.c extra_f2.c main.c
OBJ = {SRC = .c=.o};

all:
	$(CC) $(CFLAGS) $(OBJ) -o $(NAME)
clean 